name: lab-03-workflow

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create and commit hello.txt
        run: docker build -t goapp .

      - name: Starting a container with created image
        run: docker run --name go-container goapp

      - name: Replace file
        run: docker cp go-container:hello.txt $GITHUB_WORKSPACE

      - name: Remove the container
        run: docker rm go-container

      - name: Commit and push file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add hello.txt
          git commit -m "Added hello.txt"
          git push

      - name: Finishing
        run: echo "file was uploaded!"